// Auto-generated from Bluesky official app language list
// Source: https://github.com/bluesky-social/social-app/blob/main/src/locale/languages.ts

export interface Language {
  code: string;
  nameEn: string;
}

export const SUPPORTED_LANGUAGES: Language[] = [
  { code: 'aa', nameEn: 'Afar' },
  { code: 'ab', nameEn: 'Abkhazian' },
  { code: 'ace', nameEn: 'Achinese' },
  { code: 'ach', nameEn: 'Acoli' },
  { code: 'ada', nameEn: 'Adangme' },
  { code: 'ady', nameEn: 'Adyghe; Adygei' },
  { code: 'afa', nameEn: 'Afro-Asiatic languages' },
  { code: 'afh', nameEn: 'Afrihili' },
  { code: 'af', nameEn: 'Afrikaans' },
  { code: 'ain', nameEn: 'Ainu' },
  { code: 'ak', nameEn: 'Akan' },
  { code: 'akk', nameEn: 'Akkadian' },
  { code: 'sq', nameEn: 'Albanian' },
  { code: 'ale', nameEn: 'Aleut' },
  { code: 'alg', nameEn: 'Algonquian languages' },
  { code: 'alt', nameEn: 'Southern Altai' },
  { code: 'am', nameEn: 'Amharic' },
  { code: 'ang', nameEn: 'English, Old (ca.450-1100)' },
  { code: 'anp', nameEn: 'Angika' },
  { code: 'apa', nameEn: 'Apache languages' },
  { code: 'ar', nameEn: 'Arabic' },
  { code: 'arc', nameEn: 'Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)' },
  { code: 'an', nameEn: 'Aragonese' },
  { code: 'hy', nameEn: 'Armenian' },
  { code: 'arn', nameEn: 'Mapudungun; Mapuche' },
  { code: 'arp', nameEn: 'Arapaho' },
  { code: 'art', nameEn: 'Artificial languages' },
  { code: 'arw', nameEn: 'Arawak' },
  { code: 'as', nameEn: 'Assamese' },
  { code: 'ast', nameEn: 'Asturian' },
  { code: 'ath', nameEn: 'Athapascan languages' },
  { code: 'aus', nameEn: 'Australian languages' },
  { code: 'av', nameEn: 'Avaric' },
  { code: 'ae', nameEn: 'Avestan' },
  { code: 'awa', nameEn: 'Awadhi' },
  { code: 'ay', nameEn: 'Aymara' },
  { code: 'az', nameEn: 'Azerbaijani' },
  { code: 'bad', nameEn: 'Banda languages' },
  { code: 'bai', nameEn: 'Bamileke languages' },
  { code: 'ba', nameEn: 'Bashkir' },
  { code: 'bal', nameEn: 'Baluchi' },
  { code: 'bm', nameEn: 'Bambara' },
  { code: 'ban', nameEn: 'Balinese' },
  { code: 'eu', nameEn: 'Basque' },
  { code: 'bas', nameEn: 'Basa' },
  { code: 'bat', nameEn: 'Baltic languages' },
  { code: 'bej', nameEn: 'Beja; Bedawiyet' },
  { code: 'be', nameEn: 'Belarusian' },
  { code: 'bem', nameEn: 'Bemba' },
  { code: 'bn', nameEn: 'Bangla' },
  { code: 'ber', nameEn: 'Berber languages' },
  { code: 'bho', nameEn: 'Bhojpuri' },
  { code: 'bh', nameEn: 'Bhojpuri' },
  { code: 'bik', nameEn: 'Bikol' },
  { code: 'bin', nameEn: 'Bini; Edo' },
  { code: 'bi', nameEn: 'Bislama' },
  { code: 'bla', nameEn: 'Siksika' },
  { code: 'bnt', nameEn: 'Bantu languages' },
  { code: 'bo', nameEn: 'Tibetan' },
  { code: 'bs', nameEn: 'Bosnian' },
  { code: 'bra', nameEn: 'Braj' },
  { code: 'br', nameEn: 'Breton' },
  { code: 'btk', nameEn: 'Batak languages' },
  { code: 'bua', nameEn: 'Buriat' },
  { code: 'bug', nameEn: 'Buginese' },
  { code: 'bg', nameEn: 'Bulgarian' },
  { code: 'my', nameEn: 'Burmese' },
  { code: 'byn', nameEn: 'Blin; Bilin' },
  { code: 'cad', nameEn: 'Caddo' },
  { code: 'cai', nameEn: 'Central American Indian languages' },
  { code: 'car', nameEn: 'Galibi Carib' },
  { code: 'ca', nameEn: 'Catalan' },
  { code: 'cau', nameEn: 'Caucasian languages' },
  { code: 'ceb', nameEn: 'Cebuano' },
  { code: 'cel', nameEn: 'Celtic languages' },
  { code: 'cs', nameEn: 'Czech' },
  { code: 'ch', nameEn: 'Chamorro' },
  { code: 'chb', nameEn: 'Chibcha' },
  { code: 'ce', nameEn: 'Chechen' },
  { code: 'chg', nameEn: 'Chagatai' },
  { code: 'zh', nameEn: 'Chinese' },
  { code: 'chk', nameEn: 'Chuukese' },
  { code: 'chm', nameEn: 'Mari' },
  { code: 'chn', nameEn: 'Chinook jargon' },
  { code: 'cho', nameEn: 'Choctaw' },
  { code: 'chp', nameEn: 'Chipewyan; Dene Suline' },
  { code: 'chr', nameEn: 'Cherokee' },
  { code: 'cu', nameEn: 'Church Slavic' },
  { code: 'cv', nameEn: 'Chuvash' },
  { code: 'chy', nameEn: 'Cheyenne' },
  { code: 'cmc', nameEn: 'Chamic languages' },
  { code: 'cnr', nameEn: 'Serbian (Montenegro)' },
  { code: 'cop', nameEn: 'Coptic' },
  { code: 'kw', nameEn: 'Cornish' },
  { code: 'co', nameEn: 'Corsican' },
  { code: 'cpe', nameEn: 'Creoles and pidgins, English based' },
  { code: 'cpf', nameEn: 'Creoles and pidgins, French-based' },
  { code: 'cpp', nameEn: 'Creoles and pidgins, Portuguese-based' },
  { code: 'cr', nameEn: 'Cree' },
  { code: 'crh', nameEn: 'Crimean Tatar; Crimean Turkish' },
  { code: 'crp', nameEn: 'Creoles and pidgins' },
  { code: 'csb', nameEn: 'Kashubian' },
  { code: 'cus', nameEn: 'Cushitic languages' },
  { code: 'cy', nameEn: 'Welsh' },
  { code: 'cs', nameEn: 'Czech' },
  { code: 'dak', nameEn: 'Dakota' },
  { code: 'da', nameEn: 'Danish' },
  { code: 'dar', nameEn: 'Dargwa' },
  { code: 'day', nameEn: 'Land Dayak languages' },
  { code: 'del', nameEn: 'Delaware' },
  { code: 'den', nameEn: 'Slave (Athapascan)' },
  { code: 'de', nameEn: 'German' },
  { code: 'dgr', nameEn: 'Dogrib' },
  { code: 'din', nameEn: 'Dinka' },
  { code: 'dv', nameEn: 'Divehi' },
  { code: 'doi', nameEn: 'Dogri' },
  { code: 'dra', nameEn: 'Dravidian languages' },
  { code: 'dsb', nameEn: 'Lower Sorbian' },
  { code: 'dua', nameEn: 'Duala' },
  { code: 'dum', nameEn: 'Dutch, Middle (ca.1050-1350)' },
  { code: 'nl', nameEn: 'Dutch' },
  { code: 'dyu', nameEn: 'Dyula' },
  { code: 'dz', nameEn: 'Dzongkha' },
  { code: 'efi', nameEn: 'Efik' },
  { code: 'egy', nameEn: 'Egyptian (Ancient)' },
  { code: 'eka', nameEn: 'Ekajuk' },
  { code: 'el', nameEn: 'Greek' },
  { code: 'elx', nameEn: 'Elamite' },
  { code: 'en', nameEn: 'English' },
  { code: 'enm', nameEn: 'English, Middle (1100-1500)' },
  { code: 'eo', nameEn: 'Esperanto' },
  { code: 'et', nameEn: 'Estonian' },
  { code: 'eu', nameEn: 'Basque' },
  { code: 'ee', nameEn: 'Ewe' },
  { code: 'ewo', nameEn: 'Ewondo' },
  { code: 'fan', nameEn: 'Fang' },
  { code: 'fo', nameEn: 'Faroese' },
  { code: 'fa', nameEn: 'Persian' },
  { code: 'fat', nameEn: 'Akan' },
  { code: 'fj', nameEn: 'Fijian' },
  { code: 'fil', nameEn: 'Filipino' },
  { code: 'fi', nameEn: 'Finnish' },
  { code: 'fiu', nameEn: 'Finno-Ugrian languages' },
  { code: 'fon', nameEn: 'Fon' },
  { code: 'fr', nameEn: 'French' },
  { code: 'fr', nameEn: 'French' },
  { code: 'frm', nameEn: 'French, Middle (ca.1400-1600)' },
  { code: 'fro', nameEn: 'French, Old (842-ca.1400)' },
  { code: 'frr', nameEn: 'Northern Frisian' },
  { code: 'frs', nameEn: 'Eastern Frisian' },
  { code: 'fy', nameEn: 'Western Frisian' },
  { code: 'ff', nameEn: 'Fulah' },
  { code: 'fur', nameEn: 'Friulian' },
  { code: 'gaa', nameEn: 'Ga' },
  { code: 'gay', nameEn: 'Gayo' },
  { code: 'gba', nameEn: 'Gbaya' },
  { code: 'gem', nameEn: 'Germanic languages' },
  { code: 'ka', nameEn: 'Georgian' },
  { code: 'de', nameEn: 'German' },
  { code: 'gez', nameEn: 'Geez' },
  { code: 'gil', nameEn: 'Gilbertese' },
  { code: 'gd', nameEn: 'Scottish Gaelic' },
  { code: 'ga', nameEn: 'Irish' },
  { code: 'gl', nameEn: 'Galician' },
  { code: 'gv', nameEn: 'Manx' },
  { code: 'gmh', nameEn: 'German, Middle High (ca.1050-1500)' },
  { code: 'goh', nameEn: 'German, Old High (ca.750-1050)' },
  { code: 'gon', nameEn: 'Gondi' },
  { code: 'gor', nameEn: 'Gorontalo' },
  { code: 'got', nameEn: 'Gothic' },
  { code: 'grb', nameEn: 'Grebo' },
  { code: 'grc', nameEn: 'Ancient Greek' },
  { code: 'el', nameEn: 'Greek' },
  { code: 'gn', nameEn: 'Guarani' },
  { code: 'gsw', nameEn: 'Swiss German; Alemannic; Alsatian' },
  { code: 'gu', nameEn: 'Gujarati' },
  { code: 'hai', nameEn: 'Haida' },
  { code: 'ht', nameEn: 'Haitian Creole' },
  { code: 'ha', nameEn: 'Hausa' },
  { code: 'haw', nameEn: 'Hawaiian' },
  { code: 'he', nameEn: 'Hebrew' },
  { code: 'hz', nameEn: 'Herero' },
  { code: 'hil', nameEn: 'Hiligaynon' },
  { code: 'him', nameEn: 'Himachali languages; Western Pahari languages' },
  { code: 'hi', nameEn: 'Hindi' },
  { code: 'hit', nameEn: 'Hittite' },
  { code: 'hmn', nameEn: 'Hmong' },
  { code: 'ho', nameEn: 'Hiri Motu' },
  { code: 'hr', nameEn: 'Croatian' },
  { code: 'hsb', nameEn: 'Upper Sorbian' },
  { code: 'hu', nameEn: 'Hungarian' },
  { code: 'hup', nameEn: 'Hupa' },
  { code: 'hy', nameEn: 'Armenian' },
  { code: 'iba', nameEn: 'Iban' },
  { code: 'ig', nameEn: 'Igbo' },
  { code: 'is', nameEn: 'Icelandic' },
  { code: 'io', nameEn: 'Ido' },
  { code: 'ii', nameEn: 'Sichuan Yi; Nuosu' },
  { code: 'ijo', nameEn: 'Ijo languages' },
  { code: 'iu', nameEn: 'Inuktitut' },
  { code: 'ie', nameEn: 'Interlingue' },
  { code: 'ilo', nameEn: 'Iloko' },
  { code: 'ia', nameEn: 'Interlingua' },
  { code: 'inc', nameEn: 'Indic languages' },
  { code: 'id', nameEn: 'Indonesian' },
  { code: 'ine', nameEn: 'Indo-European languages' },
  { code: 'inh', nameEn: 'Ingush' },
  { code: 'ik', nameEn: 'Inupiaq' },
  { code: 'ira', nameEn: 'Iranian languages' },
  { code: 'iro', nameEn: 'Iroquoian languages' },
  { code: 'is', nameEn: 'Icelandic' },
  { code: 'it', nameEn: 'Italian' },
  { code: 'jv', nameEn: 'Javanese' },
  { code: 'jbo', nameEn: 'Lojban' },
  { code: 'ja', nameEn: 'Japanese' },
  { code: 'jpr', nameEn: 'Judeo-Persian' },
  { code: 'jrb', nameEn: 'Judeo-Arabic' },
  { code: 'kaa', nameEn: 'Kara-Kalpak' },
  { code: 'kab', nameEn: 'Kabyle' },
  { code: 'kac', nameEn: 'Kachin; Jingpho' },
  { code: 'kl', nameEn: 'Kalaallisut' },
  { code: 'kam', nameEn: 'Kamba' },
  { code: 'kn', nameEn: 'Kannada' },
  { code: 'kar', nameEn: 'Karen languages' },
  { code: 'ks', nameEn: 'Kashmiri' },
  { code: 'ka', nameEn: 'Georgian' },
  { code: 'kr', nameEn: 'Kanuri' },
  { code: 'kaw', nameEn: 'Kawi' },
  { code: 'kk', nameEn: 'Kazakh' },
  { code: 'kbd', nameEn: 'Kabardian' },
  { code: 'kha', nameEn: 'Khasi' },
  { code: 'khi', nameEn: 'Khoisan languages' },
  { code: 'km', nameEn: 'Khmer' },
  { code: 'kho', nameEn: 'Khotanese; Sakan' },
  { code: 'ki', nameEn: 'Kikuyu; Gikuyu' },
  { code: 'rw', nameEn: 'Kinyarwanda' },
  { code: 'ky', nameEn: 'Kyrgyz' },
  { code: 'kmb', nameEn: 'Kimbundu' },
  { code: 'kok', nameEn: 'Konkani' },
  { code: 'kv', nameEn: 'Komi' },
  { code: 'kg', nameEn: 'Kongo' },
  { code: 'ko', nameEn: 'Korean' },
  { code: 'kos', nameEn: 'Kosraean' },
  { code: 'kpe', nameEn: 'Kpelle' },
  { code: 'krc', nameEn: 'Karachay-Balkar' },
  { code: 'krl', nameEn: 'Karelian' },
  { code: 'kro', nameEn: 'Kru languages' },
  { code: 'kru', nameEn: 'Kurukh' },
  { code: 'kj', nameEn: 'Kuanyama; Kwanyama' },
  { code: 'kum', nameEn: 'Kumyk' },
  { code: 'ku', nameEn: 'Kurdish' },
  { code: 'kut', nameEn: 'Kutenai' },
  { code: 'lad', nameEn: 'Ladino' },
  { code: 'lah', nameEn: 'Lahnda' },
  { code: 'lam', nameEn: 'Lamba' },
  { code: 'lo', nameEn: 'Lao' },
  { code: 'la', nameEn: 'Latin' },
  { code: 'lv', nameEn: 'Latvian' },
  { code: 'lez', nameEn: 'Lezghian' },
  { code: 'li', nameEn: 'Limburgish' },
  { code: 'ln', nameEn: 'Lingala' },
  { code: 'lt', nameEn: 'Lithuanian' },
  { code: 'lol', nameEn: 'Mongo' },
  { code: 'loz', nameEn: 'Lozi' },
  { code: 'lb', nameEn: 'Luxembourgish' },
  { code: 'lua', nameEn: 'Luba-Lulua' },
  { code: 'lu', nameEn: 'Luba-Katanga' },
  { code: 'lg', nameEn: 'Ganda' },
  { code: 'lui', nameEn: 'Luiseno' },
  { code: 'lun', nameEn: 'Lunda' },
  { code: 'luo', nameEn: 'Luo (Kenya and Tanzania)' },
  { code: 'lus', nameEn: 'Mizo' },
  { code: 'mk', nameEn: 'Macedonian' },
  { code: 'mad', nameEn: 'Madurese' },
  { code: 'mag', nameEn: 'Magahi' },
  { code: 'mh', nameEn: 'Marshallese' },
  { code: 'mai', nameEn: 'Maithili' },
  { code: 'mak', nameEn: 'Makasar' },
  { code: 'ml', nameEn: 'Malayalam' },
  { code: 'man', nameEn: 'Mandingo' },
  { code: 'mi', nameEn: 'Māori' },
  { code: 'map', nameEn: 'Austronesian languages' },
  { code: 'mr', nameEn: 'Marathi' },
  { code: 'mas', nameEn: 'Masai' },
  { code: 'ms', nameEn: 'Malay' },
  { code: 'mdf', nameEn: 'Moksha' },
  { code: 'mdr', nameEn: 'Mandar' },
  { code: 'men', nameEn: 'Mende' },
  { code: 'mga', nameEn: 'Irish, Middle (900-1200)' },
  { code: 'min', nameEn: 'Minangkabau' },
  { code: 'mis', nameEn: 'Uncoded languages' },
  { code: 'mk', nameEn: 'Macedonian' },
  { code: 'mkh', nameEn: 'Mon-Khmer languages' },
  { code: 'mg', nameEn: 'Malagasy' },
  { code: 'mt', nameEn: 'Maltese' },
  { code: 'mnc', nameEn: 'Manchu' },
  { code: 'mni', nameEn: 'Manipuri' },
  { code: 'mno', nameEn: 'Manobo languages' },
  { code: 'moh', nameEn: 'Mohawk' },
  { code: 'mn', nameEn: 'Mongolian' },
  { code: 'mos', nameEn: 'Mossi' },
  { code: 'mi', nameEn: 'Māori' },
  { code: 'ms', nameEn: 'Malay' },
  { code: 'mul', nameEn: 'Multiple languages' },
  { code: 'mun', nameEn: 'Munda languages' },
  { code: 'mus', nameEn: 'Creek' },
  { code: 'mwl', nameEn: 'Mirandese' },
  { code: 'mwr', nameEn: 'Marwari' },
  { code: 'my', nameEn: 'Burmese' },
  { code: 'myn', nameEn: 'Mayan languages' },
  { code: 'myv', nameEn: 'Erzya' },
  { code: 'nah', nameEn: 'Nahuatl languages' },
  { code: 'nai', nameEn: 'North American Indian languages' },
  { code: 'nap', nameEn: 'Neapolitan' },
  { code: 'na', nameEn: 'Nauru' },
  { code: 'nv', nameEn: 'Navajo' },
  { code: 'nr', nameEn: 'South Ndebele' },
  { code: 'nd', nameEn: 'North Ndebele' },
  { code: 'ng', nameEn: 'Ndonga' },
  { code: 'nds', nameEn: 'Low German; Low Saxon; German, Low; Saxon, Low' },
  { code: 'ne', nameEn: 'Nepali' },
  { code: 'new', nameEn: 'Nepal Bhasa; Newari' },
  { code: 'nia', nameEn: 'Nias' },
  { code: 'nic', nameEn: 'Niger-Kordofanian languages' },
  { code: 'niu', nameEn: 'Niuean' },
  { code: 'nl', nameEn: 'Dutch' },
  { code: 'nn', nameEn: 'Norwegian Nynorsk' },
  { code: 'nb', nameEn: 'Norwegian Bokmål' },
  { code: 'nog', nameEn: 'Nogai' },
  { code: 'non', nameEn: 'Norse, Old' },
  { code: 'no', nameEn: 'Norwegian' },
  { code: 'nso', nameEn: 'Northern Sotho' },
  { code: 'nub', nameEn: 'Nubian languages' },
  { code: 'nwc', nameEn: 'Classical Newari; Old Newari; Classical Nepal Bhasa' },
  { code: 'ny', nameEn: 'Nyanja' },
  { code: 'nym', nameEn: 'Nyamwezi' },
  { code: 'nyn', nameEn: 'Nyankole' },
  { code: 'nyo', nameEn: 'Nyoro' },
  { code: 'nzi', nameEn: 'Nzima' },
  { code: 'oc', nameEn: 'Occitan' },
  { code: 'oj', nameEn: 'Ojibwa' },
  { code: 'or', nameEn: 'Odia' },
  { code: 'om', nameEn: 'Oromo' },
  { code: 'osa', nameEn: 'Osage' },
  { code: 'os', nameEn: 'Ossetic' },
  { code: 'ota', nameEn: 'Turkish, Ottoman (1500-1928)' },
  { code: 'oto', nameEn: 'Otomian languages' },
  { code: 'paa', nameEn: 'Papuan languages' },
  { code: 'pag', nameEn: 'Pangasinan' },
  { code: 'pal', nameEn: 'Pahlavi' },
  { code: 'pam', nameEn: 'Pampanga; Kapampangan' },
  { code: 'pa', nameEn: 'Punjabi' },
  { code: 'pap', nameEn: 'Papiamento' },
  { code: 'pau', nameEn: 'Palauan' },
  { code: 'peo', nameEn: 'Persian, Old (ca.600-400 B.C.)' },
  { code: 'fa', nameEn: 'Persian' },
  { code: 'phi', nameEn: 'Philippine languages' },
  { code: 'phn', nameEn: 'Phoenician' },
  { code: 'pi', nameEn: 'Pali' },
  { code: 'pl', nameEn: 'Polish' },
  { code: 'pon', nameEn: 'Pohnpeian' },
  { code: 'pt', nameEn: 'Portuguese' },
  { code: 'pra', nameEn: 'Prakrit languages' },
  { code: 'pro', nameEn: 'Provençal, Old (to 1500);Occitan, Old (to 1500)' },
  { code: 'ps', nameEn: 'Pashto' },
  { code: 'qu', nameEn: 'Quechua' },
  { code: 'raj', nameEn: 'Rajasthani' },
  { code: 'rap', nameEn: 'Rapanui' },
  { code: 'rar', nameEn: 'Rarotongan; Cook Islands Maori' },
  { code: 'roa', nameEn: 'Romance languages' },
  { code: 'rm', nameEn: 'Romansh' },
  { code: 'rom', nameEn: 'Romany' },
  { code: 'ro', nameEn: 'Romanian' },
  { code: 'ro', nameEn: 'Romanian' },
  { code: 'rn', nameEn: 'Rundi' },
  { code: 'rup', nameEn: 'Aromanian; Arumanian; Macedo-Romanian' },
  { code: 'ru', nameEn: 'Russian' },
  { code: 'sad', nameEn: 'Sandawe' },
  { code: 'sg', nameEn: 'Sango' },
  { code: 'sah', nameEn: 'Yakut' },
  { code: 'sai', nameEn: 'South American Indian languages' },
  { code: 'sal', nameEn: 'Salishan languages' },
  { code: 'sam', nameEn: 'Samaritan Aramaic' },
  { code: 'sa', nameEn: 'Sanskrit' },
  { code: 'sas', nameEn: 'Sasak' },
  { code: 'sat', nameEn: 'Santali' },
  { code: 'scn', nameEn: 'Sicilian' },
  { code: 'sco', nameEn: 'Scots' },
  { code: 'sel', nameEn: 'Selkup' },
  { code: 'sem', nameEn: 'Semitic languages' },
  { code: 'sga', nameEn: 'Irish, Old (to 900)' },
  { code: 'sgn', nameEn: 'Sign Languages' },
  { code: 'shn', nameEn: 'Shan' },
  { code: 'sid', nameEn: 'Sidamo' },
  { code: 'si', nameEn: 'Sinhala' },
  { code: 'sio', nameEn: 'Siouan languages' },
  { code: 'sit', nameEn: 'Sino-Tibetan languages' },
  { code: 'sla', nameEn: 'Slavic languages' },
  { code: 'sk', nameEn: 'Slovak' },
  { code: 'sk', nameEn: 'Slovak' },
  { code: 'sl', nameEn: 'Slovenian' },
  { code: 'sma', nameEn: 'Southern Sami' },
  { code: 'se', nameEn: 'Northern Sami' },
  { code: 'smi', nameEn: 'Sami languages' },
  { code: 'smj', nameEn: 'Lule Sami' },
  { code: 'smn', nameEn: 'Inari Sami' },
  { code: 'sm', nameEn: 'Samoan' },
  { code: 'sms', nameEn: 'Skolt Sami' },
  { code: 'sn', nameEn: 'Shona' },
  { code: 'sd', nameEn: 'Sindhi' },
  { code: 'snk', nameEn: 'Soninke' },
  { code: 'sog', nameEn: 'Sogdian' },
  { code: 'so', nameEn: 'Somali' },
  { code: 'son', nameEn: 'Songhai languages' },
  { code: 'st', nameEn: 'Southern Sotho' },
  { code: 'es', nameEn: 'Spanish' },
  { code: 'sq', nameEn: 'Albanian' },
  { code: 'sc', nameEn: 'Sardinian' },
  { code: 'srn', nameEn: 'Sranan Tongo' },
  { code: 'sr', nameEn: 'Serbian' },
  { code: 'srr', nameEn: 'Serer' },
  { code: 'ssa', nameEn: 'Nilo-Saharan languages' },
  { code: 'ss', nameEn: 'Swati' },
  { code: 'suk', nameEn: 'Sukuma' },
  { code: 'su', nameEn: 'Sundanese' },
  { code: 'sus', nameEn: 'Susu' },
  { code: 'sux', nameEn: 'Sumerian' },
  { code: 'sw', nameEn: 'Swahili' },
  { code: 'sv', nameEn: 'Swedish' },
  { code: 'syc', nameEn: 'Classical Syriac' },
  { code: 'syr', nameEn: 'Syriac' },
  { code: 'ty', nameEn: 'Tahitian' },
  { code: 'tai', nameEn: 'Tai languages' },
  { code: 'ta', nameEn: 'Tamil' },
  { code: 'tt', nameEn: 'Tatar' },
  { code: 'te', nameEn: 'Telugu' },
  { code: 'tem', nameEn: 'Timne' },
  { code: 'ter', nameEn: 'Tereno' },
  { code: 'tet', nameEn: 'Tetum' },
  { code: 'tg', nameEn: 'Tajik' },
  { code: 'tl', nameEn: 'Filipino' },
  { code: 'th', nameEn: 'Thai' },
  { code: 'bo', nameEn: 'Tibetan' },
  { code: 'tig', nameEn: 'Tigre' },
  { code: 'ti', nameEn: 'Tigrinya' },
  { code: 'tiv', nameEn: 'Tiv' },
  { code: 'tkl', nameEn: 'Tokelau' },
  { code: 'tlh', nameEn: 'Klingon; tlhIngan-Hol' },
  { code: 'tli', nameEn: 'Tlingit' },
  { code: 'tmh', nameEn: 'Tamashek' },
  { code: 'tog', nameEn: 'Tonga (Nyasa)' },
  { code: 'to', nameEn: 'Tongan' },
  { code: 'tpi', nameEn: 'Tok Pisin' },
  { code: 'tsi', nameEn: 'Tsimshian' },
  { code: 'tn', nameEn: 'Tswana' },
  { code: 'ts', nameEn: 'Tsonga' },
  { code: 'tk', nameEn: 'Turkmen' },
  { code: 'tum', nameEn: 'Tumbuka' },
  { code: 'tup', nameEn: 'Tupi languages' },
  { code: 'tr', nameEn: 'Turkish' },
  { code: 'tut', nameEn: 'Altaic languages' },
  { code: 'tvl', nameEn: 'Tuvalu' },
  { code: 'tw', nameEn: 'Akan' },
  { code: 'tyv', nameEn: 'Tuvinian' },
  { code: 'udm', nameEn: 'Udmurt' },
  { code: 'uga', nameEn: 'Ugaritic' },
  { code: 'ug', nameEn: 'Uyghur' },
  { code: 'uk', nameEn: 'Ukrainian' },
  { code: 'umb', nameEn: 'Umbundu' },
  { code: 'und', nameEn: 'Undetermined' },
  { code: 'ur', nameEn: 'Urdu' },
  { code: 'uz', nameEn: 'Uzbek' },
  { code: 'vai', nameEn: 'Vai' },
  { code: 've', nameEn: 'Venda' },
  { code: 'vi', nameEn: 'Vietnamese' },
  { code: 'vo', nameEn: 'Volapük' },
  { code: 'vot', nameEn: 'Votic' },
  { code: 'wak', nameEn: 'Wakashan languages' },
  { code: 'wal', nameEn: 'Wolaitta; Wolaytta' },
  { code: 'war', nameEn: 'Waray' },
  { code: 'was', nameEn: 'Washo' },
  { code: 'cy', nameEn: 'Welsh' },
  { code: 'wen', nameEn: 'Sorbian languages' },
  { code: 'wa', nameEn: 'Walloon' },
  { code: 'wo', nameEn: 'Wolof' },
  { code: 'xal', nameEn: 'Kalmyk; Oirat' },
  { code: 'xh', nameEn: 'Xhosa' },
  { code: 'yao', nameEn: 'Yao' },
  { code: 'yap', nameEn: 'Yapese' },
  { code: 'yi', nameEn: 'Yiddish' },
  { code: 'yo', nameEn: 'Yoruba' },
  { code: 'ypk', nameEn: 'Yupik languages' },
  { code: 'zap', nameEn: 'Zapotec' },
  { code: 'zbl', nameEn: 'Blissymbols; Blissymbolics; Bliss' },
  { code: 'zen', nameEn: 'Zenaga' },
  { code: 'zgh', nameEn: 'Standard Moroccan Tamazight' },
  { code: 'za', nameEn: 'Zhuang; Chuang' },
  { code: 'zh', nameEn: 'Chinese' },
  { code: 'znd', nameEn: 'Zande languages' },
  { code: 'zu', nameEn: 'Zulu' },
  { code: 'zun', nameEn: 'Zuni' },
  { code: 'zza', nameEn: 'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki' }
];

export function getLanguageName(code: string, locale?: string): string {
  const lang = SUPPORTED_LANGUAGES.find(l => l.code === code);
  if (!lang) return code;

  try {
    const displayNames = new Intl.DisplayNames([locale || 'en'], { type: 'language' });
    return displayNames.of(code) || lang.nameEn;
  } catch {
    return lang.nameEn;
  }
}

export const COMMON_LANGUAGE_CODES: string[] = [
  'en',
  'zh',
  'es',
  'hi',
  'ar',
  'fr',
  'bn',
  'pt',
  'ru',
  'ja',
  'de',
  'pa',
  'jv',
  'id',
  'te',
  'tr',
  'ko',
  'mr',
  'ta',
  'vi',
  'ur',
  'it',
  'fa',
  'pl',
  'uk',
  'ro',
  'nl',
  'el',
  'gu',
  'kn',
  'ml',
  'or',
  'as',
  'ne',
  'my',
  'si',
  'th',
  'lo',
  'km',
  'bo',
  'sa',
  'he',
  'yo',
  'sw',
  'am',
  'so',
  'ha',
  'ig',
  'zu',
  'af',
  'sq',
  'hy',
  'az',
  'be',
  'bg',
  'hr',
  'cs',
  'da',
  'et',
  'fi',
  'ka',
  'hu',
  'is',
  'ga',
  'lv',
  'lt',
  'mk',
  'ms',
  'mt',
  'no',
  'ps',
  'sr',
  'sk',
  'sl',
  'sv',
  'tl',
  'tg',
  'tt',
  'uz',
  'cy',
  'eu',
  'ca',
  'gl',
  'br',
  'co',
  'fy',
  'gd',
  'gv',
  'kw',
  'an'
];